include('src\\exports.lua')
include('src\\events\\keyboard.lua')
include('src\\events\\system_flush.lua')
include('src\\events\\system_input.lua')
include('src\\events\\system_update.lua')
include('src\\events\\timer_apu.lua')
include('src\\events\\timer_fuel.lua')
include('src\\events\\timer_debug.lua')
include('src\\events\\unit_start.lua')
include('src\\events\\unit_stop.lua')

include('src\\behaviour\\autopilot.lua')
include('src\\behaviour\\electronics.lua')
include('src\\behaviour\\engines.lua')
include('src\\behaviour\\ship.lua')

include('src\\data\\aggData.lua')
include('src\\data\\config.lua')
include('src\\data\\configDatabankMap.lua')
include('src\\data\\coroutine.lua')
include('src\\data\\constructData.lua')
include('src\\data\\eventSystem.lua')
include('src\\data\\links.lua')
include('src\\data\\playerData.lua')
include('src\\data\\radar.lua')
include('src\\data\\routeDatabase.lua')
include('src\\data\\soundSystem.lua')
include('src\\data\\tankData.lua')
include('src\\data\\warpData.lua')

include('src\\helpers\\common.lua')
include('src\\helpers\\solar_system.lua')
include('src\\helpers\\table.lua')
include('src\\helpers\\vector_math.lua')

include('src\\hud\\hud.lua')

include('src\\lib\\serialize.lua')
include('src\\lib\\SVG.lua')
include('src\\version.lua')